services:
  frontend:
    container_name: modellink_frontend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass dev values explicitly (bypasses .env completely)
        - NODE_ENV=docker_development
        - REACT_APP_ENV=docker_development
        - REACT_APP_BASE_API_DEV=$REACT_APP_BASE_API_DEV
        - REACT_APP_FILES_BASE_API_DEV=$REACT_APP_FILES_BASE_API_DEV
        - REACT_APP_CLIENT_URL_DEV=$REACT_APP_CLIENT_URL_DEV
    restart: always
    # Overriding explicitly (ignores .env runtime configs)
    environment:
      - NODE_ENV=docker_development
      - REACT_APP_ENV=docker_development
      - REACT_APP_BASE_API_DEV=$REACT_APP_BASE_API_DEV
      - REACT_APP_FILES_BASE_API_DEV=$REACT_APP_FILES_BASE_API_DEV
      - REACT_APP_CLIENT_URL_DEV=$REACT_APP_CLIENT_URL_DEV
    # locally we map the port instead of just expose    
    ports:
      - "3000:3000"
    networks:
      - modelink-network

networks:
  modelink-network:
    external: true
